language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
script: ./bootstrap.py && ./configure.py && ./ninja ninja_test && ./ninja_test --gtest_filter=-SubprocessTest.SetWithLots
